---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      sentry:
        patterns:
          - "@sentry/*"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: postgres
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker-compose"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: postgres
        update-types: ["version-update:semver-major"]
      - dependency-name: redis
        update-types: ["version-update:semver-major"]
