# Global

":construction_worker: CI":
  - changed-files:
      - any-glob-to-any-file: ".github/**"
":memo: documentation":
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
":traffic_light: e2e":
  - changed-files:
      - any-glob-to-any-file: "cypress/**/*"
":file_cabinet: migrations":
  - changed-files:
      - any-glob-to-any-file: "migrations/**/*"
":test_tube: unit test":
  - changed-files:
      - any-glob-to-any-file: "test/**/*"
      - any-glob-to-any-file: "testing/**/*"
      - any-glob-to-any-file: "**/*.test.ts"

# Scopes

"scope: core":
  - changed-files:
      - any-glob-to-any-file: "packages/core/**/*"
"scope: crisp":
  - changed-files:
      - any-glob-to-any-file: "packages/crisp/**/*"
"scope: debounce":
  - changed-files:
      - any-glob-to-any-file: "packages/debounce/**/*"
"scope: devtools":
  - changed-files:
      - any-glob-to-any-file: "packages/devtools/**/*"
"scope: email":
  - changed-files:
      - any-glob-to-any-file: "packages/email/**/*"
"scope: entreprise":
  - changed-files:
      - any-glob-to-any-file: "packages/entreprise/**/*"
"scope: identite":
  - changed-files:
      - any-glob-to-any-file: "packages/identite/**/*"
"scope: insee":
  - changed-files:
      - any-glob-to-any-file: "packages/insee/**/*"
