services:
  db:
    image: postgres:17.9
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: proconnect-identite
      POSTGRES_PASSWORD: proconnect-identite
      POSTGRES_DB: proconnect-identite
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.14
    ports:
      - "6379:6379"

  demo-test-client:
    image: ghcr.io/proconnect-gouv/proconnect-test-client@sha256:14e7d6fddae5947e5713a08fd281712c47383b7292f9e6dc49777a995a56fc41 # latest
    environment:
      PORT: 3001
      # default env var can be found at https://github.com/proconnect-gouv/proconnect-test-client/blob/main/.env
      CLIENT_ID: client_id
      HOST: http://localhost:3001
      PROVIDER: http://localhost:3000/
    network_mode: "host"

  standard-client:
    image: ghcr.io/proconnect-gouv/proconnect-test-client@sha256:14e7d6fddae5947e5713a08fd281712c47383b7292f9e6dc49777a995a56fc41 # latest
    environment:
      PORT: 4000
      CLIENT_ID: standard_client_id
      CLIENT_SECRET: standard_client_secret
      HOST: http://localhost:4000
      PROVIDER: http://localhost:3000
      SCOPES: openid email profile organization
      SITE_TITLE: standard-client
      STYLESHEET_URL:
    network_mode: "host"

  proconnect-federation-client:
    image: ghcr.io/proconnect-gouv/proconnect-test-client@sha256:14e7d6fddae5947e5713a08fd281712c47383b7292f9e6dc49777a995a56fc41 # latest
    environment:
      PORT: 4001
      SITE_TITLE: proconnect-federation-client
      CLIENT_ID: proconnect_federation_client_id
      CLIENT_SECRET: proconnect_federation_client_secret
      EXTRA_PARAM_SP_NAME: ProConnect Test
      HOST: http://localhost:4001
      ID_TOKEN_SIGNED_RESPONSE_ALG: ES256
      LOGIN_HINT: unused1@yopmail.com
      PROVIDER: http://localhost:3000
      SCOPES: openid uid given_name usual_name email siren siret organizational_unit belonging_population phone chorusdt is_service_public is_public_service
      STYLESHEET_URL:
      USERINFO_SIGNED_RESPONSE_ALG: ES256
    network_mode: "host"

  maildev:
    image: maildev/maildev@sha256:180ef51f65eefebb0e7122d8308813c1fd7bff164bc440ce5a3c2feee167a810 # latest
    environment:
      MAILDEV_IP: "::"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:1080/healthz",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    network_mode: "host"

volumes:
  db-data:
