import type { InseeSiretEstablishment } from "#src/types";

export default {
  siret: "20007184300060",
  siege_social: true,
  etat_administratif: "A",
  date_fermeture: null,
  enseigne: null,
  activite_principale: {
    code: "84.11Z",
    nomenclature: "NAFRev2",
    libelle: "Administration publique générale",
  },
  tranche_effectif_salarie: {
    de: 100,
    a: 199,
    code: "22",
    date_reference: "2022",
    intitule: "100 à 199 salariés",
  },
  diffusable_commercialement: true,
  status_diffusion: "diffusible",
  date_creation: 1611702000,
  unite_legale: {
    siren: "200071843",
    rna: null,
    siret_siege_social: "20007184300060",
    type: "personne_morale",
    personne_morale_attributs: {
      raison_sociale: "CC DU VEXIN NORMAND",
      sigle: null,
    },
    personne_physique_attributs: {
      pseudonyme: null,
      prenom_usuel: null,
      prenom_1: null,
      prenom_2: null,
      prenom_3: null,
      prenom_4: null,
      nom_usage: null,
      nom_naissance: null,
      sexe: null,
    },
    categorie_entreprise: "PME",
    status_diffusion: "diffusible",
    diffusable_commercialement: true,
    forme_juridique: {
      code: "7346",
      libelle: "Communauté de communes",
    },
    activite_principale: {
      code: "84.11Z",
      nomenclature: "NAFRev2",
      libelle: "Administration publique générale",
    },
    tranche_effectif_salarie: {
      de: 100,
      a: 199,
      code: "22",
      date_reference: "2022",
      intitule: "100 à 199 salariés",
    },
    economie_sociale_et_solidaire: false,
    date_creation: 1483225200,
    etat_administratif: "A",
  },
  adresse: {
    status_diffusion: "diffusible",
    complement_adresse: null,
    numero_voie: "3",
    indice_repetition_voie: null,
    type_voie: "RUE",
    libelle_voie: "MAISON DE VATIMESNIL",
    code_postal: "27150",
    libelle_commune: "ETREPAGNY",
    libelle_commune_etranger: null,
    distribution_speciale: null,
    code_commune: "27226",
    code_cedex: null,
    libelle_cedex: null,
    code_pays_etranger: null,
    libelle_pays_etranger: null,
    acheminement_postal: {
      l1: "CC DU VEXIN NORMAND",
      l2: "",
      l3: "",
      l4: "3 RUE MAISON DE VATIMESNIL",
      l5: "",
      l6: "27150 ETREPAGNY",
      l7: "FRANCE",
    },
  },
} as InseeSiretEstablishment;
