//

import type { InseeSireneEstablishmentSiretResponseData } from "#src/types";

export default {
  siret: "39234600300198",
  siege_social: true,
  etat_administratif: "A",
  date_fermeture: null,
  enseigne: null,
  activite_principale: {
    code: "47.59A",
    nomenclature: "NAFRev2",
    libelle: "Commerce de détail de meubles",
  },
  tranche_effectif_salarie: {
    de: 3,
    a: 5,
    code: "02",
    date_reference: "2022",
    intitule: "3 à 5 salariés",
  },
  diffusable_commercialement: true,
  status_diffusion: "diffusible",
  date_creation: 1561932000,
  unite_legale: {
    siren: "392346003",
    rna: null,
    siret_siege_social: "39234600300198",
    type: "personne_morale",
    personne_morale_attributs: {
      raison_sociale: "PAPILLON",
      sigle: null,
    },
    personne_physique_attributs: {
      pseudonyme: null,
      prenom_usuel: null,
      prenom_1: null,
      prenom_2: null,
      prenom_3: null,
      prenom_4: null,
      nom_usage: null,
      nom_naissance: null,
      sexe: null,
    },
    categorie_entreprise: "PME",
    status_diffusion: "diffusible",
    diffusable_commercialement: true,
    forme_juridique: {
      code: "5710",
      libelle: "SAS, société par actions simplifiée",
    },
    activite_principale: {
      code: "47.59A",
      nomenclature: "NAFRev2",
      libelle: "Commerce de détail de meubles",
    },
    tranche_effectif_salarie: {
      de: 10,
      a: 19,
      code: "11",
      date_reference: "2022",
      intitule: "10 à 19 salariés",
    },
    economie_sociale_et_solidaire: false,
    date_creation: 747612000,
    etat_administratif: "A",
  },
  adresse: {
    status_diffusion: "diffusible",
    complement_adresse: "5-7",
    numero_voie: "5",
    indice_repetition_voie: null,
    type_voie: "RUE",
    libelle_voie: "DU MOULIN AUX MOINES",
    code_postal: "72650",
    libelle_commune: "LA CHAPELLE-SAINT-AUBIN",
    libelle_commune_etranger: null,
    distribution_speciale: null,
    code_commune: "72065",
    code_cedex: null,
    libelle_cedex: null,
    code_pays_etranger: null,
    libelle_pays_etranger: null,
    acheminement_postal: {
      l1: "PAPILLON",
      l2: "",
      l3: "5-7",
      l4: "5 RUE DU MOULIN AUX MOINES",
      l5: "",
      l6: "72650 LA CHAPELLE-SAINT-AUBIN",
      l7: "FRANCE",
    },
  },
} as InseeSireneEstablishmentSiretResponseData;
