import type { InseeSireneEstablishmentSiretResponseData } from "#src/types";

export default {
  siret: "43841606700017",
  siege_social: true,
  etat_administratif: "A",
  date_fermeture: null,
  enseigne: "STIHLE FRERES",
  activite_principale: {
    code: "43.22B",
    nomenclature: "NAFRev2",
    libelle:
      "Travaux d'installation d'équipements thermiques et de climatisation",
  },
  tranche_effectif_salarie: {
    de: 20,
    a: 49,
    code: "12",
    date_reference: "2022",
    intitule: "20 à 49 salariés",
  },
  diffusable_commercialement: true,
  status_diffusion: "diffusible",
  date_creation: 993938400,
  unite_legale: {
    siren: "438416067",
    rna: null,
    siret_siege_social: "43841606700017",
    type: "personne_morale",
    personne_morale_attributs: {
      raison_sociale: "STIHLE FRERES",
      sigle: null,
    },
    personne_physique_attributs: {
      pseudonyme: null,
      prenom_usuel: null,
      prenom_1: null,
      prenom_2: null,
      prenom_3: null,
      prenom_4: null,
      nom_usage: null,
      nom_naissance: null,
      sexe: null,
    },
    categorie_entreprise: "ETI",
    status_diffusion: "diffusible",
    diffusable_commercialement: true,
    forme_juridique: {
      code: "5710",
      libelle: "SAS, société par actions simplifiée",
    },
    activite_principale: {
      code: "43.22B",
      nomenclature: "NAFRev2",
      libelle:
        "Travaux d'installation d'équipements thermiques et de climatisation",
    },
    tranche_effectif_salarie: {
      de: 20,
      a: 49,
      code: "12",
      date_reference: "2022",
      intitule: "20 à 49 salariés",
    },
    economie_sociale_et_solidaire: false,
    date_creation: 993938400,
    etat_administratif: "A",
  },
  adresse: {
    status_diffusion: "diffusible",
    complement_adresse: null,
    numero_voie: "7",
    indice_repetition_voie: null,
    type_voie: "RUE",
    libelle_voie: "DE LA FECHT",
    code_postal: "68230",
    libelle_commune: "WIHR-AU-VAL",
    libelle_commune_etranger: null,
    distribution_speciale: null,
    code_commune: "68368",
    code_cedex: null,
    libelle_cedex: null,
    code_pays_etranger: null,
    libelle_pays_etranger: null,
    acheminement_postal: {
      l1: "STIHLE FRERES",
      l2: "",
      l3: "",
      l4: "7 RUE DE LA FECHT",
      l5: "",
      l6: "68230 WIHR-AU-VAL",
      l7: "FRANCE",
    },
  },
} as InseeSireneEstablishmentSiretResponseData;
