/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/realms/apim-gravitee/protocol/openid-connect/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Obtenir le jeton JWT indispensable pour pouvoir interroger l'API Sirene. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            client_id: string;
            client_secret: string;
            /** @enum {string} */
            grant_type: "password";
            password: string;
            username: string;
          };
        };
      };
      responses: {
        /** @description Requête traitée avec succès */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ResponseToken"];
          };
        };
        /** @description Requête invalide */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      error: string;
      error_description: string;
    };
    /** @description Objet renvoyé en cas de succès sur une requête de type token */
    ResponseToken: {
      /** @description Jeton d'accès */
      access_token?: string;
      /** @description Durée avant expiration du jeton d'accès en secondes */
      expires_in?: number;
      /** @description Durée avant expiration du jeton de rafraîchissement en secondes */
      refresh_expires_in?: number;
      /** @description Type de jeton d'accès */
      token_type?: string;
      /** @description Durée avant la date de fin de validité du jeton d'accès en secondes */
      "not-before-policy"?: number;
      /** @description État de la session */
      session_state?: string;
      /** @description Liste des scopes autorisés */
      scope?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
