import type { InseeSiretEstablishment } from "#src/types";

export default {
  siret: "78824266700020",
  siege_social: true,
  etat_administratif: "A",
  date_fermeture: null,
  enseigne: "MEGEVAND SAS",
  activite_principale: {
    code: "43.99C",
    nomenclature: "NAFRev2",
    libelle: "Travaux de maçonnerie générale et gros œuvre de bâtiment",
  },
  tranche_effectif_salarie: {
    de: 50,
    a: 99,
    code: "21",
    date_reference: "2022",
    intitule: "50 à 99 salariés",
  },
  diffusable_commercialement: true,
  status_diffusion: "diffusible",
  date_creation: 536626800,
  unite_legale: {
    siren: "788242667",
    rna: null,
    siret_siege_social: "78824266700020",
    type: "personne_morale",
    personne_morale_attributs: {
      raison_sociale: "MEGEVAND SAS",
      sigle: null,
    },
    personne_physique_attributs: {
      pseudonyme: null,
      prenom_usuel: null,
      prenom_1: null,
      prenom_2: null,
      prenom_3: null,
      prenom_4: null,
      nom_usage: null,
      nom_naissance: null,
      sexe: null,
    },
    categorie_entreprise: "PME",
    status_diffusion: "diffusible",
    diffusable_commercialement: true,
    forme_juridique: {
      code: "5710",
      libelle: "SAS, société par actions simplifiée",
    },
    activite_principale: {
      code: "43.99C",
      nomenclature: "NAFRev2",
      libelle: "Travaux de maçonnerie générale et gros œuvre de bâtiment",
    },
    tranche_effectif_salarie: {
      de: 50,
      a: 99,
      code: "21",
      date_reference: "2022",
      intitule: "50 à 99 salariés",
    },
    economie_sociale_et_solidaire: false,
    date_creation: 94690800,
    etat_administratif: "A",
  },
  adresse: {
    status_diffusion: "diffusible",
    complement_adresse: "ZA IMMEUBLE L'OCTOGONE",
    numero_voie: "226",
    indice_repetition_voie: null,
    type_voie: "RUE",
    libelle_voie: "DU JURA",
    code_postal: "74160",
    libelle_commune: "NEYDENS",
    libelle_commune_etranger: null,
    distribution_speciale: null,
    code_commune: "74201",
    code_cedex: null,
    libelle_cedex: null,
    code_pays_etranger: null,
    libelle_pays_etranger: null,
    acheminement_postal: {
      l1: "MEGEVAND SAS",
      l2: "",
      l3: "ZA IMMEUBLE L'OCTOGONE",
      l4: "226 RUE DU JURA",
      l5: "",
      l6: "74160 NEYDENS",
      l7: "FRANCE",
    },
  },
} as InseeSiretEstablishment;
