import type { InseeSireneEstablishmentSiretResponseData } from "#src/types";

export default {
  siret: "84951084700015",
  siege_social: true,
  etat_administratif: "A",
  date_fermeture: null,
  enseigne: null,
  activite_principale: {
    code: "55.20Z",
    nomenclature: "NAFRev2",
    libelle: "Hébergement touristique et autre hébergement de courte durée",
  },
  tranche_effectif_salarie: {
    de: null,
    a: null,
    code: "NN",
    date_reference: null,
    intitule: "Unités non employeuses",
  },
  diffusable_commercialement: true,
  status_diffusion: "diffusible",
  date_creation: 1551394800,
  unite_legale: {
    siren: "849510847",
    rna: null,
    siret_siege_social: "84951084700015",
    type: "personne_physique",
    personne_morale_attributs: { raison_sociale: null, sigle: null },
    personne_physique_attributs: {
      pseudonyme: null,
      prenom_usuel: "FERGUS",
      prenom_1: "FERGUS",
      prenom_2: null,
      prenom_3: null,
      prenom_4: null,
      nom_usage: null,
      nom_naissance: "MACDONALD",
      sexe: "M",
    },
    categorie_entreprise: "PME",
    status_diffusion: "diffusible",
    diffusable_commercialement: true,
    forme_juridique: {
      code: "1000",
      libelle: "Entrepreneur individuel",
    },
    activite_principale: {
      code: "55.20Z",
      nomenclature: "NAFRev2",
      libelle: "Hébergement touristique et autre hébergement de courte durée",
    },
    tranche_effectif_salarie: {
      de: null,
      a: null,
      code: "NN",
      date_reference: null,
      intitule: "Unités non employeuses",
    },
    economie_sociale_et_solidaire: null,
    date_creation: 1551394800,
    etat_administratif: "A",
  },
  adresse: {
    status_diffusion: "diffusible",
    complement_adresse: null,
    numero_voie: "4",
    indice_repetition_voie: null,
    type_voie: "LIEU-DIT",
    libelle_voie: "BECHEMOURE",
    code_postal: "87200",
    libelle_commune: "SAINT-MARTIN-DE-JUSSAC",
    libelle_commune_etranger: null,
    distribution_speciale: null,
    code_commune: "87164",
    code_cedex: null,
    libelle_cedex: null,
    code_pays_etranger: null,
    libelle_pays_etranger: null,
    acheminement_postal: {
      l1: "",
      l2: "MACDONALD FERGUS",
      l3: "",
      l4: "4 LIEU-DIT BECHEMOURE",
      l5: "",
      l6: "87200 SAINT-MARTIN-DE-JUSSAC",
      l7: "FRANCE",
    },
  },
} as InseeSireneEstablishmentSiretResponseData;
