name: Fixtures tests

on:
  push:

env:
  ACCESS_LOG_PATH:
  DATABASE_URL: postgres://proconnect-identite:proconnect-identite@127.0.0.1:5432/proconnect-identite
  NODE_ENV: test
  PGDATABASE: proconnect-identite
  PGHOST: 127.0.0.1
  PGPASSWORD: proconnect-identite
  PGPORT: 5432
  PGUSER: proconnect-identite
  SMTP_URL: smtp://localhost:1025
  SYMMETRIC_ENCRYPTION_KEY: aTrueRandom32BytesLongBase64EncodedStringAA=

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.9
        env:
          POSTGRES_USER: ${{ env.PGUSER }}
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
          POSTGRES_DB: ${{ env.PGDATABASE }}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version-file: package.json
      - run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
          NPM_CONFIG_AUDIT: false
          NPM_CONFIG_FUND: false
          NPM_CONFIG_UPDATE_NOTIFIER: false
      - run: npm run build:workspaces
      - run: npm run migrate up
      - run: npm run fixtures:load-ci -- scripts/fixtures.sql
      - run: npm run update-organization-info -- 0
      - run: npm --workspace=@proconnect-gouv/proconnect.identite.database run test
