name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version-file: package.json
      - run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
      - run: npm run build:workspaces
      - run: npm run test:lint
      - run: npm run test:workspaces
      - run: npm run test:type-check
      - run: npm run test:unit
